import { Link } from "react-router-dom";
import { Sidebar } from "../components";
import { GrLinkPrevious, GrNext } from "react-icons/gr";
import { FaFolder } from "react-icons/fa";
import { DataGrid } from "@mui/x-data-grid";

const columns = [
  { field: "number", headerName: "ID", width: 100 },
  {
    field: "day",
    headerName: "Дата создание",
    width: 150,
  },
  {
    field: "address",
    headerName: "Адресс клиента",
    width: 310,
  },
  {
    field: "sum",
    headerName: "Сумма",
    width: 130,
  },
  { field: "firstName", headerName: "Оператор", width: 220 },
  {
    field: "name",
    headerName: "Филиал",
    width: 90,
  },
  {
    field: "delivery",
    headerName: "Тип доставки",
    width: 120,
  },
  {
    field: "bot",
    headerName: "Источник",
    width: 120,
  },
];

const rows = [
  {
    id: 1,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 2,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 3,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 4,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 5,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 6,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 7,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 8,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 9,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 10,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 11,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 12,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 13,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 14,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 15,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 16,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 17,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 18,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 19,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 20,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 21,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 22,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 23,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 24,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 25,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 26,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 27,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 28,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 29,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 30,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 31,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 32,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 33,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 34,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 35,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 36,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 37,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 38,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 39,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 40,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 41,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 42,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 43,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 44,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 45,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 46,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 47,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 48,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 49,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 50,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 51,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 52,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 53,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 54,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 55,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 56,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 57,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 58,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 59,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 60,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 61,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 62,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 63,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 64,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 65,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 66,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 67,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 68,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 69,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 70,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 71,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 72,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 73,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 74,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 75,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 76,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 77,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 78,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 79,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 80,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 81,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 82,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 83,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
  {
    id: 84,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 85,
    firstName: "Абдумансуров Абдукаххор",
    number: "5262261",
    day: "10.03.2021",
    sum: "1 000 000 сум",
    name: "Oqtepa",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 86,
    firstName: "Комилжонов Бехруз",
    number: "6373372",
    day: "11.11.2021",
    sum: "900 000 сум",
    name: "Chilonzor",
    delivery: "Доставка",
    bot: "Телеграм бот",
    address: "ул. Байкальская‚ д. 52‚ кв. 22",
  },
];

const ClientsOrders = () => {
  return (
    <div className="flex">
      <Sidebar />
      <div className="w-[1292px] pt-4">
        <Link to="/clients">
          <p className="m-4 flex text-[#B0BABF]">
            <GrLinkPrevious />
            <span className="ml-4">
              <FaFolder />
            </span>
            <span className="-m-[6px] ml-3">Клиенты</span>
          </p>
        </Link>
        <div className="-mt-8 ml-36 text-[#b0babf]">
          <GrNext />
        </div>
        <div className="-mt-4 ml-44 flex text-[#4094F7]">
          <FaFolder />
          <span className="-mt-1 ml-2 text-black">Eleanor Pena</span>
        </div>
        <div className="pt-4">
          <hr />
          <div className="h-[40px] bg-[#6E8BB70D] p-2 text-[#6E8BB7]">
            <Link
              to="/clients/about-clients"
              className="ml-4 cursor-pointer hover:text-[#4094f7]"
            >
              О клиенте
            </Link>
            <Link
              to="/clients/about-clients/orders"
              className="ml-4 cursor-pointer hover:text-[#4094f7]"
            >
              Заказы
            </Link>
          </div>
        </div>
        <div className="flex h-[965px] bg-[#4094F726]">
          <div className="m-4 h-[13.4rem] cursor-pointer bg-white">
            <DataGrid
              rows={rows}
              columns={columns}
              initialState={{
                pagination: {
                  paginationModel: { page: 0, pageSize: 2 },
                },
              }}
              pageSizeOptions={[10, 20]}
            />
          </div>
        </div>
      </div>
    </div>
  );
};

export default ClientsOrders;
