import { DataGrid } from "@mui/x-data-grid";
import { CgSearch } from "react-icons/cg";
import { Sidebar } from "../components";
import Calendar from "../calendar/Calendar";

const columns = [
  { field: "id", headerName: "№", width: 10 },
  { field: "firstName", headerName: "Клиент", width: 200 },
  { field: "number", headerName: "Ид.заказа", width: 100 },
  {
    field: "time",
    headerName: "Таймер",
    width: 90,
  },
  {
    field: "no",
    headerName: "Курьер",
    width: 80,
  },
  {
    field: "name",
    headerName: "Филиал",
    width: 90,
  },
  {
    field: "delivery",
    headerName: "Тип доставки",
    width: 120,
  },
  {
    field: "price",
    headerName: "Цена заказа",
    width: 120,
  },
  {
    field: "address",
    headerName: "Адресс клиента",
    width: 330,
  },
];

const rows = [
  {
    id: 1,
    firstName: "Арсений Морозов",
    number: "5262261",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 2,
    firstName: "Дамир Баранов",
    number: "5637657",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 3,
    firstName: "Вероника Новикова",
    number: "5425683",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 4,
    firstName: "Денис Андреев",
    number: "9003237",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 5,
    firstName: "Дмитрий Лебедев",
    number: "9232734",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 6,
    firstName: "Елизавета Фёдорова",
    number: "5227365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 7,
    firstName: "Марьяна Соловьёва",
    number: "9232735",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 8,
    firstName: "Ева Васильева",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 9,
    firstName: "Амелия Белова",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 10,
    firstName: "Павел Титов",
    number: "6426778",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 11,
    firstName: "Павел Титов",
    number: "6426778",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 12,
    firstName: "Амелия Белова",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 13,
    firstName: "Ева Васильева",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 14,
    firstName: "Марьяна Соловьёва",
    number: "9232735",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 15,
    firstName: "Елизавета Фёдорова",
    number: "5227365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 16,
    firstName: "Дмитрий Лебедев",
    number: "9232734",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 17,
    firstName: "Денис Андреев",
    number: "9003237",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 18,
    firstName: "Вероника Новикова",
    number: "5425683",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 19,
    firstName: "Дамир Баранов",
    number: "5637657",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 20,
    firstName: "Арсений Морозов",
    number: "5262261",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 21,
    firstName: "Арсений Морозов",
    number: "5262261",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 22,
    firstName: "Дамир Баранов",
    number: "5637657",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 23,
    firstName: "Вероника Новикова",
    number: "5425683",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 24,
    firstName: "Денис Андреев",
    number: "9003237",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 25,
    firstName: "Дмитрий Лебедев",
    number: "9232734",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 26,
    firstName: "Елизавета Фёдорова",
    number: "5227365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 27,
    firstName: "Марьяна Соловьёва",
    number: "9232735",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 28,
    firstName: "Ева Васильева",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 29,
    firstName: "Амелия Белова",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 30,
    firstName: "Павел Титов",
    number: "6426778",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 31,
    firstName: "Павел Титов",
    number: "6426778",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 32,
    firstName: "Амелия Белова",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 33,
    firstName: "Ева Васильева",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 34,
    firstName: "Марьяна Соловьёва",
    number: "9232735",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 35,
    firstName: "Елизавета Фёдорова",
    number: "5227365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 36,
    firstName: "Дмитрий Лебедев",
    number: "9232734",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 37,
    firstName: "Денис Андреев",
    number: "9003237",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 38,
    firstName: "Вероника Новикова",
    number: "5425683",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 39,
    firstName: "Дамир Баранов",
    number: "5637657",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 40,
    firstName: "Арсений Морозов",
    number: "5262261",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 41,
    firstName: "Арсений Морозов",
    number: "5262261",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 42,
    firstName: "Дамир Баранов",
    number: "5637657",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 43,
    firstName: "Вероника Новикова",
    number: "5425683",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 44,
    firstName: "Денис Андреев",
    number: "9003237",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 45,
    firstName: "Дмитрий Лебедев",
    number: "9232734",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 46,
    firstName: "Елизавета Фёдорова",
    number: "5227365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 47,
    firstName: "Марьяна Соловьёва",
    number: "9232735",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 48,
    firstName: "Ева Васильева",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 49,
    firstName: "Амелия Белова",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 50,
    firstName: "Павел Титов",
    number: "6426778",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 51,
    firstName: "Павел Титов",
    number: "6426778",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 52,
    firstName: "Амелия Белова",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 53,
    firstName: "Ева Васильева",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 54,
    firstName: "Марьяна Соловьёва",
    number: "9232735",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 55,
    firstName: "Елизавета Фёдорова",
    number: "5227365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 56,
    firstName: "Дмитрий Лебедев",
    number: "9232734",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 57,
    firstName: "Денис Андреев",
    number: "9003237",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 58,
    firstName: "Вероника Новикова",
    number: "5425683",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 59,
    firstName: "Дамир Баранов",
    number: "5637657",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 60,
    firstName: "Арсений Морозов",
    number: "5262261",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 61,
    firstName: "Арсений Морозов",
    number: "5262261",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 62,
    firstName: "Дамир Баранов",
    number: "5637657",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 63,
    firstName: "Вероника Новикова",
    number: "5425683",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 64,
    firstName: "Денис Андреев",
    number: "9003237",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 65,
    firstName: "Дмитрий Лебедев",
    number: "9232734",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 66,
    firstName: "Елизавета Фёдорова",
    number: "5227365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 67,
    firstName: "Марьяна Соловьёва",
    number: "9232735",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 68,
    firstName: "Ева Васильева",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 69,
    firstName: "Амелия Белова",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 70,
    firstName: "Павел Титов",
    number: "6426778",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 71,
    firstName: "Павел Титов",
    number: "6426778",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 72,
    firstName: "Амелия Белова",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 73,
    firstName: "Ева Васильева",
    number: "7527365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 74,
    firstName: "Марьяна Соловьёва",
    number: "9232735",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 75,
    firstName: "Елизавета Фёдорова",
    number: "5227365",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 76,
    firstName: "Дмитрий Лебедев",
    number: "9232734",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 77,
    firstName: "Денис Андреев",
    number: "9003237",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 78,
    firstName: "Вероника Новикова",
    number: "5425683",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 79,
    firstName: "Дамир Баранов",
    number: "5637657",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 80,
    firstName: "Арсений Морозов",
    number: "5262261",
    time: "02:33:48",
    no: "—",
    name: "Chilonzor",
    delivery: "Доставка",
    price: "$999",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 81,
    firstName: "Арсений Морозов",
    number: "5262261",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 82,
    firstName: "Дамир Баранов",
    number: "5637657",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 83,
    firstName: "Вероника Новикова",
    number: "5425683",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 84,
    firstName: "Денис Андреев",
    number: "9003237",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
  {
    id: 85,
    firstName: "Дмитрий Лебедев",
    number: "9232734",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "ул. Байкальская‚ д.52‚ кв.22",
  },
  {
    id: 86,
    firstName: "Елизавета Фёдорова",
    number: "5227365",
    time: "02:33:48",
    no: "—",
    name: "Oqtepa",
    delivery: "Доставка",
    price: "$888",
    address: "Ташкент г. Алмазар р.Янги Алмазар у.51",
  },
];

export default function Table() {
  return (
    <div className="flex">
      <Sidebar />
      <div>
        <p className="m-3 ml-5 text-2xl font-bold">Заказы</p>
        <div className="mb-4 ml-4 flex h-[32px] w-[400px] border text-gray-500">
          <div className="flex p-2">
            <CgSearch />
            <input
              type="text"
              placeholder="Поиск..."
              className="h-1 p-2 focus:outline-none"
            />
          </div>
        </div>
        <div className="-mt-12 ml-[60%] w-[300px] pb-4">
          <Calendar />
        </div>
        <div className="flex h-[965px] w-[1292px] bg-[#4094F726]">
          <div className="m-8 cursor-pointer bg-white">
            <DataGrid
              rows={rows}
              columns={columns}
              initialState={{
                pagination: {
                  paginationModel: { page: 0, pageSize: 15 },
                },
              }}
              pageSizeOptions={[10, 20]}
              checkboxSelection
            />
          </div>
        </div>
      </div>
    </div>
  );
}
